<section class="grid cols-2 knowledge-overview"><article class="card"><span class="section-kicker">RAG CURADO</span><h2>Documentos pequenos, específicos e versionados</h2><p class="muted">O agente deve recuperar somente documentos publicados do sistema e público corretos. Segredos, dados pessoais e suposições não entram na base.</p></article><article class="card"><span class="section-kicker">REGRA DE RESPOSTA</span><h2>Sem evidência, sem invenção</h2><p class="muted">Quando não houver conteúdo suficiente, o agente abre ou encaminha um ticket e informa claramente a limitação.</p></article></section>
<section class="card knowledge-form-card"><h2>Novo documento</h2><form method="post" action="/conhecimento" class="form-grid"><?= csrf_field() ?>
  <label>Sistema <select name="system_id" required><?php foreach ($systems as $system): ?><option value="<?= e($system['id']) ?>"><?= e($system['name']) ?></option><?php endforeach; ?></select></label><label>Título <input name="title" required></label><label>Slug opcional <input name="slug"></label>
  <label>Tipo <select name="document_type"><option value="guide">Guia</option><option value="faq">FAQ</option><option value="runbook">Runbook interno</option><option value="policy">Política</option><option value="troubleshooting">Diagnóstico</option></select></label>
  <label>Público <select name="audience"><option value="customer">Cliente</option><option value="support" selected>Suporte</option><option value="admin">Administrador</option><option value="agent">Agente</option></select></label><label>Estado <select name="status"><option value="draft">Rascunho</option><option value="review">Revisão</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select></label>
  <label>Idioma <select name="language"><option>pt-BR</option><option>en</option><option>es</option></select></label><label class="span-2">Tags <input name="tags" placeholder="login, acesso, senha"></label><label class="span-3">Resumo <textarea name="summary" placeholder="Quando este documento deve ser recuperado"></textarea></label><label class="span-3">Conteúdo em Markdown <textarea class="knowledge-content" name="content" required placeholder="# Objetivo&#10;## Procedimento&#10;## Quando escalar"></textarea></label><label class="span-3">Fonte verificável <input name="source_path" placeholder="docs/arquivo.md, rota ou versão do produto"></label><div class="actions"><button>Salvar documento</button></div>
</form></section>
<section class="card knowledge-list"><div class="card-heading"><div><span class="section-kicker">ACERVO</span><h2><?= count($documents) ?> documentos</h2></div><form method="get" action="/conhecimento" class="filter-row"><select name="system_id"><option value="0">Todos os sistemas</option><?php foreach ($systems as $system): ?><option value="<?= e($system['id']) ?>" <?= $systemId === (int)$system['id'] ? 'selected' : '' ?>><?= e($system['name']) ?></option><?php endforeach; ?></select><select name="status"><option value="">Todos os estados</option><?php foreach (['draft','review','published','archived'] as $value): ?><option <?= $status === $value ? 'selected' : '' ?>><?= $value ?></option><?php endforeach; ?></select><button>Filtrar</button></form></div>
<?php foreach ($documents as $document): ?><article class="knowledge-row"><div><span class="section-kicker"><?= e($document['system_name']) ?> · <?= e($document['document_type']) ?> · <?= e($document['audience']) ?></span><h3><?= e($document['title']) ?></h3><p class="muted"><?= e($document['summary']) ?></p><small><?= e($document['tags']) ?> · v<?= e($document['version']) ?> · ~<?= e($document['token_estimate']) ?> tokens</small></div><form method="post" action="/conhecimento/atualizar" class="status-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($document['id']) ?>"><select name="status"><?php foreach (['draft','review','published','archived'] as $value): ?><option <?= $document['status'] === $value ? 'selected' : '' ?>><?= $value ?></option><?php endforeach; ?></select><button>Alterar</button></form></article><?php endforeach; ?>
</section>
