<?php $isAccountant=(\App\Core\Auth::user()['role']??'')==='accountant'; ?>
<?php if(!empty($_SESSION['flash'])):?><div class="alert"><?=e($_SESSION['flash']);unset($_SESSION['flash']);?></div><?php endif;?>
<?php if(!empty($_SESSION['flash_success'])):?><div class="alert alert-success"><?=e($_SESSION['flash_success']);unset($_SESSION['flash_success']);?></div><?php endif;?>
<?php if($section==='dashboard'):?>
<section class="module-hero accounting-hero"><div><span class="hero-label">PORTAL CONTABIL SEGURO</span><h2>Documentos, comunicacao e prestacao de contas em um so lugar.</h2><p>Arquivos protegidos e registro de cada download para acompanhamento administrativo.</p></div><div class="hero-orbit"><span>DOC</span></div></section>
<section class="grid metric-grid"><div class="card metric metric-blue"><span class="metric-icon">#</span><div><span class="muted">Documentos</span><strong><?=count($documents)?></strong><small>Arquivo centralizado</small></div></div><div class="card metric metric-amber"><span class="metric-icon">!</span><div><span class="muted">Sem acesso</span><strong><?=$summary['unread']?></strong><small>Aguardando o contador</small></div></div><div class="card metric metric-green"><span class="metric-icon">OK</span><div><span class="muted">Competencia</span><strong><?=e($summary['month'])?></strong><small>Periodo corrente</small></div></div><div class="card metric metric-violet"><span class="metric-icon">MSG</span><div><span class="muted">Pendencias</span><strong><?=$summary['open_messages']?></strong><small>Mensagens em aberto</small></div></div></section>
<nav class="module-actions" aria-label="Recursos da contabilidade"><a class="module-action" href="/contabilidade?view=documentos"><b>Documentos</b><span>Arquivos, boletos e comprovantes</span><i>→</i></a><a class="module-action" href="/contabilidade?view=mensagens"><b>Mensagens</b><span>Solicitacoes e pendencias</span><i>→</i></a><?php if(!$isAccountant):?><a class="module-action" href="/contabilidade?view=acessos"><b>Acessos</b><span>Usuarios exclusivos do contador</span><i>→</i></a><?php endif;?><a class="module-action" href="/contabilidade?view=relatorios"><b>Relatorios</b><span>Resumo financeiro por competencia</span><i>→</i></a></nav>
<?php else:?><div class="module-page-head"><div><span class="section-kicker">DOC CONTABILIDADE</span><h2><?=e(ucfirst($section))?></h2></div><a class="btn secondary-button" href="/contabilidade">Voltar ao painel</a></div><?php endif;?>

<?php if($section==='documentos'):?><section class="grid cols-2 module-grid"><?php if(!$isAccountant):?><div class="card"><div class="card-heading compact"><h2>Disponibilizar documento</h2></div><form method="post" action="/contabilidade/documentos" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><label class="span-2">Titulo<input name="title" required></label><label>Categoria<select name="category"><option value="invoice">Nota fiscal</option><option value="bank_slip">Boleto</option><option value="payment_receipt">Comprovante</option><option value="bank_statement">Extrato</option><option value="contract">Contrato</option><option value="tax">Imposto/guia</option><option value="payroll">Folha/pro-labore</option><option value="other">Outro</option></select></label><label>Competencia<input type="month" name="reference_month" value="<?=date('Y-m')?>"></label><label class="span-2">Arquivo PDF/JPG/PNG<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></label><label class="span-3">Observacoes<textarea name="notes"></textarea></label><button>Enviar ao contador</button></form></div><?php endif;?><div class="card data-card <?=!$isAccountant?'':'span-2'?>"><div class="card-heading compact"><h2>Central de arquivos</h2></div><div class="table-wrap"><table><thead><tr><th>Competencia</th><th>Documento</th><th>Categoria</th><th>Downloads</th><th>Ultimo acesso</th><th></th></tr></thead><tbody><?php foreach($documents as $d):?><tr><td><?=e($d['reference_month']?:'-')?></td><td><strong><?=e($d['title'])?></strong><br><small><?=e($d['original_name'])?></small></td><td><span class="badge"><?=e($d['category'])?></span></td><td><?=$d['downloads']?></td><td><?=$d['last_access_at']?e($d['last_access_at']):'<span class="badge warning">Nao acessado</span>'?></td><td><a class="btn small-button" href="/contabilidade/documentos/download?id=<?=$d['id']?>">Baixar</a></td></tr><?php endforeach;?><?php if(!$documents):?><tr><td colspan="6" class="empty-state">Nenhum documento.</td></tr><?php endif;?></tbody></table></div></div></section><?php endif;?>

<?php if($section==='mensagens'):?><section class="grid cols-2 module-grid"><div class="card"><div class="card-heading compact"><h2>Nova solicitacao ou recado</h2></div><form method="post" action="/contabilidade/mensagens" class="stack-form"><?=csrf_field()?><label>Assunto<input name="subject" required></label><label>Prazo desejado<input type="date" name="due_date"></label><label>Mensagem<textarea name="message" required></textarea></label><button>Registrar mensagem</button></form></div><div class="card data-card"><div class="card-heading compact"><h2>Historico e pendencias</h2></div><div class="table-wrap"><table><thead><tr><th>Remetente</th><th>Assunto</th><th>Prazo</th><th>Status</th></tr></thead><tbody><?php foreach($messages as $m):?><tr><td><?=e($m['sender_name'])?></td><td><strong><?=e($m['subject'])?></strong><br><small><?=e($m['message'])?></small></td><td><?=e($m['due_date']?:'-')?></td><td><span class="badge <?=$m['status']==='open'?'warning':'success'?>"><?=e($m['status'])?></span></td></tr><?php endforeach;?><?php if(!$messages):?><tr><td colspan="4" class="empty-state">Sem mensagens.</td></tr><?php endif;?></tbody></table></div></div></section><?php endif;?>

<?php if($section==='acessos'&&!$isAccountant):?><section class="grid cols-2 module-grid"><div class="card"><div class="card-heading compact"><h2>Novo acesso exclusivo</h2></div><form method="post" action="/contabilidade/contador" class="stack-form"><?=csrf_field()?><label>Nome do contador/escritorio<input name="name" required></label><label>E-mail de acesso<input type="email" name="email" required></label><label>Senha inicial<input type="password" name="password" minlength="10" required></label><button>Criar acesso restrito</button></form></div><div class="card data-card"><div class="card-heading compact"><h2>Usuarios da contabilidade</h2></div><div class="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Criado em</th><th>Status</th></tr></thead><tbody><?php foreach($accountants as $a):?><tr><td><?=e($a['name'])?></td><td><?=e($a['email'])?></td><td><?=e($a['created_at'])?></td><td><span class="badge <?=$a['active']?'success':'warning'?>"><?=$a['active']?'Ativo':'Inativo'?></span></td></tr><?php endforeach;?><?php if(!$accountants):?><tr><td colspan="4" class="empty-state">Nenhum contador cadastrado.</td></tr><?php endif;?></tbody></table></div></div></section><?php endif;?>

<?php if($section==='relatorios'):?><section class="card module-card"><div class="card-heading"><div><span class="section-kicker">EXPORTACAO</span><h2>Resumo financeiro mensal</h2></div></div><form method="get" action="/contabilidade/relatorio" class="form-grid module-inner"><label>Competencia<input type="month" name="month" value="<?=date('Y-m')?>"></label><div class="actions"><button>Exportar resumo CSV</button></div></form></section><?php endif;?>
