<?php if(!empty($_SESSION['flash'])):?><div class="alert"><?=e($_SESSION['flash']);unset($_SESSION['flash']);?></div><?php endif;?>
<?php if(!empty($_SESSION['flash_success'])):?><div class="alert alert-success"><?=e($_SESSION['flash_success']);unset($_SESSION['flash_success']);?></div><?php endif;?>
<div class="module-page-head"><div><span class="section-kicker">PRODUCAO 3D</span><h2>Entrada de notas fiscais</h2></div><a class="btn secondary-button" href="/impressao-3d">Voltar ao painel</a></div>
<section class="grid cols-2 module-grid">
 <div class="card"><div class="card-heading compact"><div><span class="section-kicker">IMPORTACAO NF-E</span><h2><?=$preview?'Substituir XML em conferencia':'Ler XML autorizado'?></h2></div></div><form method="post" action="/impressao-3d/notas-fiscais/importar" enctype="multipart/form-data" class="stack-form"><?=csrf_field()?><label>Novo arquivo XML da NF-e<input type="file" name="xml" accept="application/xml,text/xml,.xml" required></label><?php if($preview):?><small>O novo arquivo substituira a conferencia atual.</small><?php endif;?><button><?=$preview?'Carregar outro XML':'Ler XML para conferencia'?></button></form></div>
 <div class="card"><div class="card-heading compact"><h2>O que sera registrado</h2></div><div class="invoice-help"><p>Chave, numero, serie, emissao, fornecedor, totais e todos os itens da nota.</p><p>Depois da leitura, voce confere item a item quais produtos geram lotes, material, cor, rolos e peso.</p><p>O custo de aquisicao considera proporcionalmente o total da nota, incluindo frete e descontos.</p><p>O XML original fica privado e notas repetidas sao bloqueadas pela chave.</p></div></div>
</section>

<?php if($preview):?>
<section class="card data-card module-card"><div class="card-heading"><div><span class="section-kicker">CONFERENCIA OBRIGATORIA</span><h2>NF-e <?=e($preview['data']['number'])?> · <?=e($preview['data']['issuer_name'])?></h2></div><strong><?=money($preview['data']['total_invoice'])?></strong></div>
 <?php if($preview['data']['expense_origin']==='owner_personal'):?><div class="alert">Emitida para o titular. A conta a pagar sera classificada em 2.12 · Despesas operacionais pagas pelo titular.</div><?php endif;?>
 <form method="post" action="/impressao-3d/notas-fiscais/confirmar" class="module-inner"><?=csrf_field()?><div class="table-wrap"><table><thead><tr><th>Gerar lote</th><th>Item da nota</th><th>Qtd.</th><th>Material</th><th>Cor</th><th>Rolos</th><th>Peso total (g)</th><th>Custo fiscal</th></tr></thead><tbody>
 <?php foreach($preview['data']['items'] as $item): $n=(string)$item['number'];$details=$item['filament_details'];?><tr><td><input type="checkbox" name="filament[<?=e($n)?>]" value="1" <?=$item['is_filament']?'checked':''?> aria-label="Gerar lote para item <?=e($n)?>"></td><td><strong><?=e($item['code'])?> · <?=e($item['description'])?></strong><br><small>NCM <?=e($item['ncm'])?> · CFOP <?=e($item['cfop'])?></small></td><td><?=number_format($item['quantity'],4,',','.')?> <?=e($item['unit'])?></td><td><select name="material[<?=e($n)?>]"><?php foreach(['PLA','PETG','ABS','TPU','ASA','Nylon','Resina','Outro'] as $material):?><option <?=$details['material']===$material?'selected':''?>><?=$material?></option><?php endforeach;?></select></td><td><input name="color[<?=e($n)?>]" value="<?=e($details['color'])?>" maxlength="80"></td><td><input type="number" min="0.01" step="0.01" name="spool_quantity[<?=e($n)?>]" value="<?=e($details['spool_quantity'])?>"></td><td><input type="number" min="1" step="0.01" name="weight_g[<?=e($n)?>]" value="<?=e($details['total_weight_g'])?>"></td><td><?=money($preview['data']['total_products']>0?$preview['data']['total_invoice']*($item['total_price']/$preview['data']['total_products']):$item['total_price'])?></td></tr><?php endforeach;?>
 </tbody></table></div><div class="invoice-confirm"><label class="checkbox-label"><input type="checkbox" name="create_payable" value="1" data-payable-toggle> Gerar conta a pagar</label><label data-payable-date hidden>Vencimento<input type="date" name="due_date" value="<?=date('Y-m-d')?>"></label><button>Confirmar entrada fiscal e estoque</button></div></form>
</section>
<?php endif;?>

<?php if($selectedInvoice):?><section class="card data-card module-card"><div class="card-heading"><div><span class="section-kicker">CONFERENCIA DA NF-E <?=e($selectedInvoice['invoice_number'])?></span><h2>Itens importados</h2></div><a class="btn secondary-button small-button" href="/impressao-3d/notas-fiscais">Fechar detalhes</a></div><div class="table-wrap"><table><thead><tr><th>Item</th><th>Codigo / Descricao</th><th>NCM</th><th>CFOP</th><th>Qtd.</th><th>Unitario</th><th>Total</th><th>Lote</th></tr></thead><tbody><?php foreach($selectedItems as $item):?><tr><td><?=$item['item_number']?></td><td><strong><?=e($item['supplier_product_code']?:'-')?> · <?=e($item['description'])?></strong><br><small><?=e($item['ean']?:'Sem GTIN')?></small></td><td><?=e($item['ncm']?:'-')?></td><td><?=e($item['cfop']?:'-')?></td><td><?=number_format($item['quantity'],4,',','.')?> <?=e($item['unit'])?></td><td><?=money($item['unit_price'])?></td><td><?=money($item['total_price'])?></td><td><?=$item['inventory_code']?'<span class="badge success">'.e($item['inventory_code']).'</span>':'-'?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>

<section class="card data-card module-card"><div class="card-heading"><div><span class="section-kicker">HISTORICO FISCAL</span><h2>Notas importadas</h2></div></div><div class="table-wrap"><table><thead><tr><th>Emissao</th><th>NF-e</th><th>Origem</th><th>Fornecedor</th><th>Itens</th><th>Filamentos</th><th>Total</th><th>Acoes</th></tr></thead><tbody><?php foreach($invoices as $n):?><tr><td><?=e(substr($n['issued_at'],0,10))?></td><td><strong><?=e($n['invoice_number'])?></strong><br><small>Serie <?=e($n['series'])?> · <?=e($n['access_key'])?></small></td><td><span class="badge <?=($n['expense_origin']??'company')==='owner_personal'?'warning':'success'?>"><?=($n['expense_origin']??'company')==='owner_personal'?'Titular':'Empresa'?></span></td><td><?=e($n['supplier_name']?:$n['issuer_name'])?><br><small><?=e($n['issuer_document'])?></small></td><td><?=$n['item_count']?></td><td><span class="badge <?=$n['filament_count']?'success':''?>"><?=$n['filament_count']?> lote(s)</span></td><td><strong><?=money($n['total_invoice'])?></strong></td><td class="actions"><a class="btn small-button" href="/impressao-3d/notas-fiscais?id=<?=$n['id']?>">Detalhes</a><a class="btn secondary-button small-button" href="/impressao-3d/notas-fiscais/xml?id=<?=$n['id']?>">XML</a></td></tr><?php endforeach;?><?php if(!$invoices):?><tr><td colspan="8" class="empty-state">Nenhuma NF-e importada.</td></tr><?php endif;?></tbody></table></div></section>
