<?php
namespace App\Controllers;

use App\Core\Auth;use App\Core\Controller;use App\Core\Database;use App\Services\NfeXmlService;use RuntimeException;use Throwable;

final class FiscalInvoiceController extends Controller
{
 public function index():void{$this->allowAdmin();$db=Database::connection();$invoices=$db->query("select n.*,s.name supplier_name,count(i.id) item_count,coalesce(sum(case when i.is_filament then 1 else 0 end),0) filament_count from fiscal_invoices n left join suppliers_3d s on s.id=n.supplier_id left join fiscal_invoice_items i on i.fiscal_invoice_id=n.id group by n.id,s.name order by n.issued_at desc,n.id desc limit 100")->fetchAll();$selectedInvoice=null;$selectedItems=[];$id=(int)$this->input('id');if($id){$s=$db->prepare('select * from fiscal_invoices where id=:id');$s->execute(['id'=>$id]);$selectedInvoice=$s->fetch()?:null;if($selectedInvoice){$s=$db->prepare('select i.*,f.inventory_code from fiscal_invoice_items i left join filaments_3d f on f.id=i.filament_id where i.fiscal_invoice_id=:id order by i.item_number');$s->execute(['id'=>$id]);$selectedItems=$s->fetchAll();}}$preview=$_SESSION['nfe_preview']??null;if($preview&&($preview['created_at']??0)<time()-3600){$this->discardPreview();$preview=null;}if($preview){$service=new NfeXmlService();foreach($preview['data']['items'] as &$item)$item['filament_details']=$service->filamentDetails($item);unset($item);}$this->view('printing3d/invoices',compact('invoices','selectedInvoice','selectedItems','preview')+['title'=>'Notas fiscais 3D']);}

 public function import():void
 {
  $this->allowAdmin();
  $file=$_FILES['xml']??null;
  if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)$this->fail($this->uploadError((int)($file['error']??UPLOAD_ERR_NO_FILE)));
  if(($file['size']??0)>10*1024*1024||!is_uploaded_file($file['tmp_name']))$this->fail('Envie um XML de NF-e valido com ate 10 MB.');
  $contents=file_get_contents($file['tmp_name']);
  if($contents===false)$this->fail('Nao foi possivel ler o XML enviado.');

  // Um novo upload sempre substitui a conferencia em andamento.
  $this->discardPreview();
  try{
   $data=(new NfeXmlService())->parse($contents);$db=Database::connection();$s=$db->prepare('select id from fiscal_invoices where access_key=:key');$s->execute(['key'=>$data['access_key']]);if($s->fetchColumn())throw new RuntimeException('Esta NF-e ja foi importada.');$directory=$this->storageDirectory();$name='preview-'.bin2hex(random_bytes(16)).'.xml';if(file_put_contents($directory.'/'.$name,$contents,LOCK_EX)===false)throw new RuntimeException('Nao foi possivel preservar o XML para conferencia.');@chmod($directory.'/'.$name,0640);$_SESSION['nfe_preview']=['data'=>$data,'temp_name'=>$name,'created_at'=>time()];$_SESSION['flash_success']='Novo XML lido. Confira os itens antes de confirmar a entrada.';
  }catch(Throwable $e){$_SESSION['flash']=$e instanceof RuntimeException?$e->getMessage():'Nao foi possivel ler a NF-e.';}
  redirect('/impressao-3d/notas-fiscais');
 }

 public function confirm():void
 {
  $this->allowAdmin();$preview=$_SESSION['nfe_preview']??null;if(!$preview||($preview['created_at']??0)<time()-3600)$this->fail('A conferencia expirou. Envie o XML novamente.');$data=$preview['data'];$temp=$this->storageDirectory().'/'.basename($preview['temp_name']);if(!is_file($temp))$this->fail('O XML temporario nao foi encontrado.');$db=Database::connection();$final=null;
  try{$s=$db->prepare('select id from fiscal_invoices where access_key=:key');$s->execute(['key'=>$data['access_key']]);if($s->fetchColumn())throw new RuntimeException('Esta NF-e ja foi importada.');$storageName=$data['access_key'].'-'.bin2hex(random_bytes(8)).'.xml';$final=$this->storageDirectory().'/'.$storageName;if(!rename($temp,$final))throw new RuntimeException('Nao foi possivel confirmar o armazenamento do XML.');@chmod($final,0640);$db->beginTransaction();$supplierId=$this->supplier($data['issuer_name'],$data['issuer_document']);
   $s=$db->prepare('insert into fiscal_invoices(access_key,model,series,invoice_number,issued_at,supplier_id,issuer_name,issuer_document,recipient_document,expense_origin,total_products,total_freight,total_discount,total_taxes,total_invoice,xml_storage_name,imported_by) values(:access_key,:model,:series,:number,:issued_at,:supplier_id,:issuer_name,:issuer_document,:recipient_document,:expense_origin,:products,:freight,:discount,:taxes,:total,:xml,:user)');$s->execute(['access_key'=>$data['access_key'],'model'=>$data['model'],'series'=>$data['series'],'number'=>$data['number'],'issued_at'=>$data['issued_at'],'supplier_id'=>$supplierId,'issuer_name'=>$data['issuer_name'],'issuer_document'=>$data['issuer_document'],'recipient_document'=>$data['recipient_document'],'expense_origin'=>$data['expense_origin'],'products'=>$data['total_products'],'freight'=>$data['total_freight'],'discount'=>$data['total_discount'],'taxes'=>$data['total_taxes'],'total'=>$data['total_invoice'],'xml'=>$storageName,'user'=>Auth::user()['id']]);$invoiceId=(int)$db->lastInsertId();$count=0;$selected=(array)($_POST['filament']??[]);
   foreach($data['items'] as $item){$n=(string)$item['number'];$is=isset($selected[$n]);$s=$db->prepare('insert into fiscal_invoice_items(fiscal_invoice_id,item_number,supplier_product_code,ean,description,ncm,cfop,unit,quantity,unit_price,total_price,is_filament) values(:invoice,:number,:code,:ean,:description,:ncm,:cfop,:unit,:quantity,:unit_price,:total,:filament)');$s->execute(['invoice'=>$invoiceId,'number'=>$item['number'],'code'=>$item['code']?:null,'ean'=>$item['ean']?:null,'description'=>$item['description'],'ncm'=>$item['ncm']?:null,'cfop'=>$item['cfop']?:null,'unit'=>$item['unit']?:null,'quantity'=>$item['quantity'],'unit_price'=>$item['unit_price'],'total'=>$item['total_price'],'filament'=>$is?1:0]);$itemId=(int)$db->lastInsertId();if(!$is)continue;$material=$this->material((string)($_POST['material'][$n]??'Outro'));$color=mb_substr(trim((string)($_POST['color'][$n]??'')),0,80)?:null;$weight=max(0,(float)($_POST['weight_g'][$n]??0));$spools=max(0,(float)($_POST['spool_quantity'][$n]??0));if($weight<=0||$spools<=0)throw new RuntimeException('Informe peso e quantidade de rolos do item '.$item['number'].'.');$cost=$data['total_products']>0?$data['total_invoice']*($item['total_price']/$data['total_products']):$item['total_price'];$s=$db->prepare('insert into filaments_3d(supplier_id,fiscal_invoice_item_id,name,material,color,diameter_mm,spool_net_weight_g,spool_quantity,current_weight_g,purchase_price,batch_code,purchase_date,minimum_stock_g) values(:supplier,:item,:name,:material,:color,1.75,:weight,:spools,:weight,:price,:batch,:date,0)');$s->execute(['supplier'=>$supplierId,'item'=>$itemId,'name'=>$item['description'],'material'=>$material,'color'=>$color,'weight'=>$weight,'spools'=>$spools,'price'=>round($cost,2),'batch'=>'NF '.$data['number'].' item '.$item['number'],'date'=>substr($data['issued_at'],0,10)]);$filamentId=(int)$db->lastInsertId();$code='FIL-'.str_pad((string)$filamentId,6,'0',STR_PAD_LEFT);$db->prepare('update filaments_3d set inventory_code=:code where id=:id')->execute(['code'=>$code,'id'=>$filamentId]);$db->prepare('update fiscal_invoice_items set filament_id=:filament where id=:id')->execute(['filament'=>$filamentId,'id'=>$itemId]);$count++;}
   if($this->input('create_payable')==='1'){$due=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$this->input('due_date'))?$this->input('due_date'):substr($data['issued_at'],0,10);$accountCode=$data['expense_origin']==='owner_personal'?'2.12':'2.07';$a=$db->prepare('select id,name from chart_of_accounts where code=:code');$a->execute(['code'=>$accountCode]);$account=$a->fetch();if(!$account)throw new RuntimeException('Conta contabil '.$accountCode.' nao encontrada. Execute as migracoes.');$s=$db->prepare("insert into financial_entries(description,category,account_id,direction,amount,due_date,status,notes,fiscal_invoice_id,expense_origin) values(:description,:category,:account,'payable',:amount,:due,'pending',:notes,:invoice,:origin)");$s->execute(['description'=>'NF '.$data['number'].' - '.$data['issuer_name'],'category'=>$account['name'],'account'=>$account['id'],'amount'=>$data['total_invoice'],'due'=>$due,'notes'=>'Importada automaticamente do XML da NF-e.','invoice'=>$invoiceId,'origin'=>$data['expense_origin']]);}$s=$db->prepare("insert into audit_logs(admin_user_id,action,entity,entity_id,ip_address) values(:user,'import_nfe','fiscal_invoice',:id,:ip)");$s->execute(['user'=>Auth::user()['id'],'id'=>(string)$invoiceId,'ip'=>$_SERVER['REMOTE_ADDR']??null]);$db->commit();unset($_SESSION['nfe_preview']);$_SESSION['flash_success']='NF-e confirmada com '.count($data['items']).' item(ns) e '.$count.' lote(s) de filamento.';
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($final&&is_file($final))rename($final,$temp);$_SESSION['flash']=$e instanceof RuntimeException?$e->getMessage():'Nao foi possivel confirmar a NF-e.';}redirect('/impressao-3d/notas-fiscais');
 }

 public function download():void{$this->allowAdmin();$s=Database::connection()->prepare('select * from fiscal_invoices where id=:id');$s->execute(['id'=>(int)$this->input('id')]);$invoice=$s->fetch();$path=$invoice?$this->storageDirectory().'/'.$invoice['xml_storage_name']:'';if(!$invoice||!is_file($path)){http_response_code(404);exit('XML nao encontrado.');}header('Content-Type: application/xml; charset=UTF-8');header('Content-Length: '.filesize($path));header('Content-Disposition: attachment; filename="NFe-'.$invoice['access_key'].'.xml"');readfile($path);exit;}
 private function supplier(string $name,string $document):int{$db=Database::connection();foreach($db->query('select id,document_number from suppliers_3d where document_number is not null')->fetchAll() as $s)if(preg_replace('/\D/','',(string)$s['document_number'])===$document)return(int)$s['id'];$s=$db->prepare('insert into suppliers_3d(name,document_number,notes) values(:name,:document,:notes)');$s->execute(['name'=>$name,'document'=>$document,'notes'=>'Cadastrado automaticamente por importacao de NF-e.']);return(int)$db->lastInsertId();}
 private function material(string $value):string{$allowed=['PLA','PETG','ABS','TPU','ASA','Nylon','Resina','Outro'];return in_array($value,$allowed,true)?$value:'Outro';}
 private function storageDirectory():string{$directory=dirname(__DIR__,2).'/storage/fiscal-invoices';if(!is_dir($directory)&&!mkdir($directory,0770,true)&&!is_dir($directory))throw new RuntimeException('Nao foi possivel preparar o armazenamento fiscal.');return $directory;}
 private function discardPreview():void{$p=$_SESSION['nfe_preview']??null;if($p){$path=$this->storageDirectory().'/'.basename((string)($p['temp_name']??''));if(is_file($path))unlink($path);}unset($_SESSION['nfe_preview']);}
 private function uploadError(int $error):string{return match($error){UPLOAD_ERR_INI_SIZE,UPLOAD_ERR_FORM_SIZE=>'O XML excede o limite permitido de 10 MB.',UPLOAD_ERR_PARTIAL=>'O envio do XML ficou incompleto. Tente novamente.',UPLOAD_ERR_NO_FILE=>'Selecione um novo arquivo XML.',default=>'Nao foi possivel receber o XML. Tente novamente.'};}
 private function fail(string $message):never{$_SESSION['flash']=$message;redirect('/impressao-3d/notas-fiscais');}
 private function allowAdmin():void{if(!in_array(Auth::user()['role']??'',['owner','admin'],true)){http_response_code(403);exit('Acesso restrito.');}}
}
